language: python
install:
    - pip install tox coveralls
script:
    - tox
env:
    - TOXENV=py34-1.7.X
    - TOXENV=py27-1.7.X
    - TOXENV=py34-1.6.X
    - TOXENV=py27-1.6.X
after_success: coveralls
